### PR TITLE
Fb change xdebug version

### PR DESCRIPTION
**Pull request by mistermoper**
Related issue: #78

### CODE REVIEW

**Comment by csandanov** [comment]
Not sure we should add it, sounds like a very specific narrow issue to resolve. What's the problem with upgrading phpstorm to the latest version? also older xdebug version doesn't support php 7.3

**Comment by nassaz** [comment]
There are companies that have a license for a specific version of PHPSTORM, we can not force people to use a specific version of PHPSTORM for example, this argument will allow to specify the version of xdebug to use simply instead of create a specific dockerfile to do that.

**Comment by csandanov** [comment]
We don't strive to cover every possible customization someone might have, I'm pretty sure there are many companies that might need a different version of a lib or an extension. This particular option doesn't look to me like something worth customizing in the generic image. Managing your own dockerfile sounds like a good solution

**Comment by Chematronix** [comment]
Could you reconsider, @csandanov?  Xdebug 2.8+ can be considerably slower than its predecessors (25 secs. for requests that take 14 with version 2.6.1 in my case, or even more extreme in [others](https://stackoverflow.com/questions/58376863/xdebug-speed-why-is-it-so-slow-v2-6-2-2-8-0b2)).

Not sure how prevalent the problem is, but I suspect it's noticeable with any sizeable project. Seeing that @nassaz's proposal doesn't incur in any overhead, it would allow anyone that desires so to get speedier debugging without the hurdle of rolling custom images.

Cheers!

**Pull request closed without merging**
