### PR TITLE
bump EXT_MONGODB_VER to latest

### PR DESCRIPTION
**Pull request by klokie**

### CODE REVIEW

**Comment by csandanov** [comment]
As you can see latest mongodb extension doesn't compile with libressl https://github.com/mongodb/mongo-php-driver/issues/507

**Comment by klokie** [comment]
Hi, thanks for your reply to my (somewhat premature) PR, and for sharing all your great work!
After reviewing the dependency chain, it's not clear to me where libressl & alpine fit into this.

From what I can tell, running a Drupal 7 stack would includes [wodby/docker4drupal](https://github.com/wodby/docker4drupal), which composes [wodby/drupal-php](https://github.com/wodby/drupal-php/blob/master/7.0/Dockerfile), from [wodby/php](https://github.com/wodby/php/blob/master/7.0/Dockerfile), from [wodby/base-php](https://github.com/wodby/base-php/blob/master/7.0/Dockerfile), from `debian:jessie`.

The latter uses `openssl`, so I can't see where libressl & alpine come into the picture. Can you please tell me what I'm missing? I'd really like to get MongoDB 1.2.0+ working if possible.
Thanks again!

**Comment by csandanov** [comment]
Images `wodby/base-php` are alpine-based (see [.travis.yml](https://github.com/wodby/base-php/blob/master/.travis.yml#L14)), basically it's a fork of [_/php](https://github.com/docker-library/php/) but with newer alpine (3.6 instead of 3.4). 

You can use the older versions of `wodby/php` (tagged with 2.3.0 or 2.2.0) which are based on alpine 3.4 (openssl). It comes with the latest mongodb but has other issues such as segfault in imagick.

**Comment by klokie** [comment]
Ah, I see. Thanks for the pointer.
I'll have a look at the older tags. Seems like if I were to build the image myself (as I'm doing for the dependent images) I should be able to sort it out.
Cheers

**Pull request closed without merging**
