### PR TITLE
Add yarn package manager to the php image

### PR DESCRIPTION
**Pull request by spleshka**
Nowadays, js becomes more and more integrated with php. Drupal ecosystem also growth further and projects like https://www.drupal.org/project/webpack appear in the community for handling of progressively decoupled applications. Therefore js package manager accessibility alongside with php becomes more and more regularly used.

Therefore I propose to add yarn to the php image so that php images of Wodby are future-proof.

### CODE REVIEW

**Comment by csandanov** [comment]
Not sure I understand the use case, why would you need yarn in a runtime of a php backend? And why would you use a node package in a php library for a backend?

**Comment by spleshka** [comment]
Hi @csandanov, sorry for later response. Here's an answer from the webpack's module maintainer that hopefully can provide you more clarity https://www.drupal.org/project/webpack/issues/2962721#comment-12582167.

**Comment by spleshka** [comment]
@csandanov let me know if the purpose is still unclear. Having php to trigger all yarn stuff under the hood proved it's worth very well for development of Progressive Applications, so it is very valuable to have yarn available in the same container.

**Comment by csandanov** [comment]
Is this a way to install node dependencies by modules via composer.json instead of having a bunch of separate package.json and have a single location `node_modules` in the root like with `vendor`? How do modules actually use node dependencies, the only example I can come up with are themes that use node to compile static but that's only needed in the build state, not runtime. Do you perhaps have a real-life example?

**Comment by spleshka** [comment]
@csandanov let me provide a real life example and explain how it all works.

Let's imagine that we want to build a standalone module that adds a feature to a Drupal site. This feature includes both backend configs & frontend theming, but instead of using Drupal theme templates we want to use React.js in a Progressively Decoupled manner. Unfortunately, at the moment there is no standard way in Drupal core to add es6 support for javascript, as well as have a centralized webpack bundler that would track all dependencies and changes in modules and auto-reload them on change.

Therefore, there is a solution in contrib that fullfills this gap called [Webpack](https://www.drupal.org/project/webpack). It allows developers to have a `package.json` file in a root of Drupal installation (same as `composer.json`, but only for javascript dependencies) which provides centralized hub for all npm dependencies defined in different modules as well retains structure of Drupal modules allowing for simple plug & play of new modules into the ecosystem.

Here are high level technical steps:
1. Install [Webpack](https://www.drupal.org/project/webpack), [Webpack Babel](https://www.drupal.org/project/webpack_babel) and [Webpack React](https://drupal.org/project/webpack_react) modules (they all are from the same ecosystem)
2. Add empty `package.json` to the Drupal root and add npm dependencies from those installed modules to this file just like this:

```
$ yarn init -yp   in root
$ yarn add file:./web/modules/contrib/webpack
$ yarn add file:./web/modules/contrib/webpack_babel
$ yarn add react react-dom @babel/preset-react
```

3. Now we're all set for development of custom modules using React.js. Here's what we do next:

- Create a custom module
- Define a new library in the module including `webpack: true` into it ([example](https://git.drupalcode.org/project/webpack/blob/8.x-1.x/tests/modules/webpack_test_libs/webpack_test_libs.libraries.yml#L3))
- Create an empty `package.json` inside of the module and then add it to the global `package.json` like this: ```yarn add file:./web/modules/custom/my_module```
- Start webpack watching and live reloading using `drush webpack:serve --docker`. It uses php to trigger webpack (it's the most weird part, I know, but it works!)
- Add a js file to the custom module as usual which already has support for es6 and React. If we need any other npm dependency we can simply add it through `package.json` inside of a module .
- When the development is over, we call `drush webpack:build-single custom_module/library_name` and it builds a distribution js file inside of the custom module. It's ready now to be deployed to production.

### Final notes

- As you might have seen, we still use `package.json` as it's common in JS community, but webpack is being controlled by php code and therefore requires `yarn / nodejs` to be installed within the php image.
- Yarn & nodejs are required only during development / build time, not during the run time.

Here's a real module we've built for Drupal using this approach: [Anu LMS](https://github.com/systemseed/anu_lms). You can look into `anu_lms.libraries.yml` file & then `js` folder to get a sense of how it works in a real life.

**Comment by csandanov** [comment]
Added yarn to the dev version of the image

**Comment by spleshka** [comment]
Thank you!

**Pull request closed without merging**
